language: go

services:
 - docker

go:
  - '1.7.x'

go_import_path: github.com/eneco/kronjob

before_install:
  - go get -u github.com/Masterminds/glide
  - make bootstrap

script:
  - make test

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    make docker;
    fi
