apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kronjob-alwaysfail
  labels:
    app: kronjob-alwaysfail
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kronjob-alwaysfail
    spec:
      containers:
      - name: kronjob-alwaysfail
        image: eneco/kronjob:latest
        imagePullPolicy: Always
        env:
        - name: SCHEDULE
          value: "@every 15s"
        - name: TEMPLATE
          value: |-
            containers:
            - name: myjob
              image: alpine
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
              args:
                - "echo hello world; sleep 5; exit 1"
              env:
              - name: TEST
                value: "hello world"
              resources:
                limits:
                memory: 512Mi
              requests:
                memory: 256Mi
